name: Build Test
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  DOCKER_USERNAME: tiryoh
  DOCKER_IMAGENAME: ros-desktop-vnc

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[Skip CI] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  build-and-deploy:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    continue-on-error: true
    strategy:
      matrix:
        ros-distro: [kinetic, melodic, noetic]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        id: docker
        run: |
          TIMESTAMP=$(date '+%Y%m%dT%H%M')
          cd ${{ matrix.ros-distro }} && docker build -t $DOCKER_USERNAME/$DOCKER_IMAGENAME:${{ matrix.ros-distro }}-$TIMESTAMP .
          echo ::set-output name=timestamp::$TIMESTAMP

      - name: Dump docker image
        run: |
          docker save $DOCKER_USERNAME/$DOCKER_IMAGENAME:${{ matrix.ros-distro }}-${{ steps.docker.outputs.timestamp }} | gzip > ${{ matrix.ros-distro }}-${{ steps.docker.outputs.timestamp }}.tar.gz

      - uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: docker-${{ matrix.ros-distro }}-${{ steps.docker.outputs.timestamp }}
          path: ${{ matrix.ros-distro }}-${{ steps.docker.outputs.timestamp }}.tar.gz
